#!/bin/bash

if [ ! -n $SOURCE_IMAGE ] and [ ! -n $SOURCE_IMAGE_TAG ]
then
  echo "This is missing the magic!"
  exit 1
fi

# pull the existing image from the registry, if it exists, to use as a build cache
docker pull $SOURCE_IMAGE:$SOURCE_IMAGE_TAG && export IMAGE_CACHE="--cache-from $SOURCE_IMAGE:$SOURCE_IMAGE_TAG" || export IMAGE_CACHE=""

# build the image, login and push
docker build -f "$DOCKERFILE_PATH"  --build-arg MH_ARCH=$SOURCE_IMAGE --build-arg MH_TAG=$SOURCE_IMAGE_TAG -t "$DOCKER_REPO:$DOCKER_TAG" .
